### ISSUE TITLE
"User" info is included in the full_log

### ISSUE THREAD

**Issue by ddpbsd** [phirelight/perl-ossec-log-parse#1]
Perhaps this is as intended, but trying to get the full_log results in "User:" entries as well.

```
Alert: User: ddp
Nov 16 07:25:53 arrakis sudo:      ddp : TTY=ttyp1 ; PWD=/home/ddp ; USER=root ; COMMAND=/bin/ksh
```

This is the result of a simple print:

``` perl
while( my $events = $parse->getAlert() ) {
        print("Alert: $events->{full_log}\n");
}

```

**Comment by unusedPhD** [comment]
change has been made so that if group includes syslog, on the non parsed alert will be include in the full_log output.
